[PDI-18885] Performance degradation due to opening of XML files.
pentaho/pentaho-kettle pull request #7672
Opened 2020-09-05 18:05 UTC by smmribeiro

Now, before trying to read the file, the file is checked for existence.

@pentaho-lmartins @ssamora @ppatricio @bcostahitachivantara

2020-09-05 18:31 UTC, buildguy commented
### :white_check_mark: Build finished in 26m 5s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **4916**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7672/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2020-09-15 12:17 UTC, buildguy commented
### :white_check_mark: Build finished in 24m 6s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **4916**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7672/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2020-09-15 13:34 UTC, pentaho-lmartins requested changes

2020-09-15 13:34 UTC, pentaho-lmartins commented on core/src/main/resources/org/pentaho/di/core/xml/messages/messages.properties
> +XMLHandler.errorReadingFile=XUnable to read file [{0}].
Why is there an X before each message?

2020-09-15 14:16 UTC, smmribeiro commented on core/src/main/resources/org/pentaho/di/core/xml/messages/messages.properties
> +XMLHandler.errorReadingFile=XUnable to read file [{0}].
Didn't stage the final version.

2020-09-15 14:40 UTC, buildguy commented
### :white_check_mark: Build finished in 24m 58s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **4916**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7672/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2020-09-16 10:21 UTC, smmribeiro commented on core/src/main/resources/org/pentaho/di/core/xml/messages/messages.properties
> +XMLHandler.errorReadingFile=XUnable to read file [{0}].
Done (resolving).

2020-09-16 11:16 UTC, ppatricio approved these changes

2020-09-16 11:17 UTC, ppatricio commented
i18n implemented as requested & messages fixed as Luis highlighted.
Ok for merging. Waiting for @pentaho-lmartins approval.

2020-09-16 16:44 UTC, pentaho-lmartins approved these changes

2020-09-16 17:03 UTC, merged