[PDI-18916] Backport of PDI-18375 - Implement streaming prefetch with…
pentaho/pentaho-kettle pull request #7747
Opened 2020-10-22 20:18 UTC by ricksjames

… a parameter

2020-10-22 20:49 UTC, buildguy commented
### :white_check_mark: Build finished in 30m 32s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
engine,plugins/streaming/impls/jms,plugins/streaming/impls/mqtt
```
---
:ok_hand: All tests passed!
 
Tests run: **3623**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7747/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2020-10-22 21:10 UTC, rmansoor approved these changes

2020-10-22 21:11 UTC, rmansoor commented
Once I get a go ahead from @c-ferreira and @pentaho-lmartins  I will process the PR

2020-10-23 13:22 UTC, pentaho-lmartins requested changes
Please make this SP-5769.

2020-10-23 17:41 UTC, rmansoor approved these changes

2020-10-23 17:42 UTC, merged