[BACKLOG-36242][BACKLOG-36243][BACKLOG-36244][BACKLOG-36254] 1) Fix N…
pentaho/pentaho-kettle pull request #8521
Opened 2022-08-29 16:32 UTC by tkafalas

…PE on invalid save attempt

2) Implement PasswordVisibleTextVar and replace all PasswordTextVar widets.
3) Add file browse to GCS dialog.
4) Add Rename/Copy prompt when saving VFS connection after changing the name.

2022-08-29 16:49 UTC, buildguy commented
### :white_check_mark: Build finished in 16m 55s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,plugins/connections/ui,ui
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

2022-08-30 01:22 UTC, peterrinehart requested changes

2022-08-30 01:22 UTC, peterrinehart commented on core/src/main/java/org/pentaho/di/connections/ConnectionManager.java
>  package org.pentaho.di.connections;
Update the copyright date on this file

2022-08-30 01:22 UTC, peterrinehart commented on plugins/connections/ui/src/main/java/org/pentaho/di/connections/ui/dialog/ConnectionRenameDialog.java
> + * Copyright (C) 2019 by Hitachi Vantara : http://www.pentaho.com
Update the date here

2022-08-30 01:22 UTC, peterrinehart commented on ui/src/main/java/org/pentaho/di/ui/core/widget/PasswordVisibleTextVar.java
> + * Copyright (C) 2002-2017 by Hitachi Vantara : http://www.pentaho.com
Copyright date

2022-08-30 13:47 UTC, buildguy commented
### :white_check_mark: Build finished in 16m 46s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,plugins/connections/ui,ui
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

2022-08-30 20:37 UTC, ddiroma approved these changes

2022-08-30 20:37 UTC, merged