[BACKLOG-36880] Implement Object Array for metadata injections- Inser…
pentaho/pentaho-kettle pull request #8773
Opened 2023-01-09 20:39 UTC by eddie-martinez

…t/Update step

2023-01-09 21:18 UTC, buildguy commented
### :white_check_mark: Build finished in 38m 51s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine,ui
```
---
:ok_hand: All tests passed!
 
Tests run: **4030**, Failures: **0**, Skipped: **8** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi-11/job/PR-8773/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-01-10 21:11 UTC, peterrinehart approved these changes

2023-01-10 21:14 UTC, peterrinehart requested changes
Please address bugs found by SonarQube

2023-01-11 15:33 UTC, buildguy commented
### :white_check_mark: Build finished in 36m 20s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine,ui
```
---
:ok_hand: All tests passed!
 
Tests run: **4030**, Failures: **0**, Skipped: **8** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi-11/job/PR-8773/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-01-11 18:19 UTC, merged