[BACKLOG-37696][BACKLOG-37985][PDI-19777] changes:
pentaho/pentaho-kettle pull request #8987
Opened 2023-08-23 15:11 UTC by niehusa

- Changed Rest.java, add HttpClientManager.java
- Solving compilation errors
- Change pom.xml for dependencies
- Delete StringMessageBodyWriter.java & StringMessageBodyWriterTest.java
- Cleanup commented out code in Rest.java
- packaged jersey 2.x dependencies in rest-plugin/lib directory
- Temporarily commented out one test
- Remove exclusions
- Change useTransitiveDependencies to be 'true'
- Use variable for jersey-apache-connector version, change some dependencies to be provided
- Change/Add copyright header
- Implement test testCallEndpointWithGetVerb() using jersey 2.x
- Addressed comment, removed commeted out properties

2023-08-23 15:23 UTC, buildguy commented
### :white_check_mark: Build finished in 11m 40s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
plugins/rest/assemblies/plugin,plugins/rest/core
```
---
:ok_hand: All tests passed!
 
Tests run: **30**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-8987/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-08-23 16:59 UTC, pdesai16 commented on plugins/rest/core/pom.xml
> -    <jersey-client.version>1.19.1</jersey-client.version>
These commented lines can be removed

2023-08-23 18:53 UTC, buildguy commented
### :white_check_mark: Build finished in 11m 27s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
plugins/rest/assemblies/plugin,plugins/rest/core
```
---
:ok_hand: All tests passed!
 
Tests run: **30**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-8987/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-08-24 18:52 UTC, buildguy commented
### :white_check_mark: Build finished in 11m 18s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
plugins/rest/assemblies/plugin,plugins/rest/core
```
---
:ok_hand: All tests passed!
 
Tests run: **31**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-8987/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-08-24 18:56 UTC, peterrinehart requested changes

2023-08-24 18:56 UTC, peterrinehart commented on plugins/rest/core/pom.xml
> +<!--        </exclusion>-->
Do we need to keep this commented block or can we get rid of it?

2023-08-24 18:56 UTC, peterrinehart commented on plugins/rest/core/src/main/java/org/pentaho/di/util/HttpClientManager.java
> +  //    return ( hostname, session ) -> {
Is this method still needed anymore, or can we get rid of it?

2023-08-24 19:01 UTC, buildguy commented
### :white_check_mark: Build finished in 9m 11s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
plugins/rest/assemblies/plugin,plugins/rest/core
```
---
:ok_hand: All tests passed!
 
Tests run: **31**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-8987/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-08-24 19:07 UTC, peterrinehart approved these changes

2023-08-24 19:11 UTC, buildguy commented
### :white_check_mark: Build finished in 7m 10s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
plugins/rest/assemblies/plugin,plugins/rest/core
```
---
:ok_hand: All tests passed!
 
Tests run: **31**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-8987/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-08-24 19:11 UTC, merged