[BACKLOG-38577] - (10.X) -Enable additional logging for Observability
pentaho/pentaho-kettle pull request #9064
Opened 2023-10-12 13:46 UTC by lsaikrishna89

2023-10-12 14:13 UTC, peterrinehart requested changes
Please ensure this PR is linked to a jira ticket with a clear explanation of the reason for these changes.

2023-10-12 14:13 UTC, peterrinehart commented on engine/src/main/java/org/pentaho/di/trans/Trans.java
>  import org.pentaho.metastore.api.IMetaStore;
Fix the copyright date in this file, please.

2023-10-12 14:55 UTC, buildguy commented
### :warning: Build finished in 1h 8m 36s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine,ui
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.metainject.MetaInjectTest.testMetastoreIsSet</b> (click to expand)</summary><p>

```
Central Log Store is not initialized!!!
```

</p></details>

  
Tests run: **4092**, Failures: **1**, Skipped: **13** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9064/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-10-12 15:58 UTC, buildguy commented
### :warning: Build finished in 1h 3m 37s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine,ui
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.metainject.MetaInjectTest.testMetastoreIsSet</b> (click to expand)</summary><p>

```
Central Log Store is not initialized!!!
```

</p></details>

  
Tests run: **4092**, Failures: **1**, Skipped: **13** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9064/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-10-13 10:40 UTC, buildguy commented
### :warning: Build finished in 1h 2m 17s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine,ui
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.metainject.MetaInjectTest.testMetastoreIsSet</b> (click to expand)</summary><p>

```
Central Log Store is not initialized!!!
```

</p></details>

  
Tests run: **4092**, Failures: **1**, Skipped: **13** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9064/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-10-13 11:39 UTC, buildguy commented
### :warning: Build finished in 59m 23s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine,ui
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.metainject.MetaInjectTest.testMetastoreIsSet</b> (click to expand)</summary><p>

```
Central Log Store is not initialized!!!
```

</p></details>

  
Tests run: **4092**, Failures: **1**, Skipped: **13** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9064/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-10-13 12:53 UTC, buildguy commented
### :white_check_mark: Build finished in 1h 24s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
engine,plugins/meta-inject/impl,ui
```
---
:ok_hand: All tests passed!
 
Tests run: **4092**, Failures: **0**, Skipped: **13** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9064/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-10-13 13:45 UTC, peterrinehart requested changes

2023-10-13 13:45 UTC, peterrinehart commented on plugins/meta-inject/impl/src/test/java/org/pentaho/di/trans/steps/metainject/MetaInjectTest.java
>  import org.pentaho.di.core.exception.KettleValueException;
This file also needs the copyright header updated.

2023-10-13 13:53 UTC, buildguy commented
### :white_check_mark: Build finished in 59m 59s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
engine,plugins/meta-inject/impl,ui
```
---
:ok_hand: All tests passed!
 
Tests run: **4092**, Failures: **0**, Skipped: **13** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9064/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-10-16 07:24 UTC, buildguy commented
### :white_check_mark: Build finished in 59m 52s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
engine,plugins/meta-inject/impl,ui
```
---
:ok_hand: All tests passed!
 
Tests run: **4092**, Failures: **0**, Skipped: **13** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9064/7/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-10-16 20:12 UTC, lsaikrishna89 commented
closing the following PR as it has two commits unable to squash them, so I have opened the new PR
https://github.com/pentaho/pentaho-kettle/pull/9069

2023-10-16 20:12 UTC, closed without merging