Backlog 38663
pentaho/pentaho-kettle pull request #9070
Opened 2023-10-18 06:03 UTC by lsaikrishna89

2023-10-18 06:06 UTC, buildguy commented
### :x: Build failed in 2m 27s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

2023-10-19 20:37 UTC, smmribeiro requested changes
Code does not seem right...

2023-10-19 20:37 UTC, smmribeiro commented on assemblies/core/lib/pom.xml
> +        <!--<sqlite-jdbc.version>3.27.2.1</sqlite-jdbc.version>-->
Why comment and not simply remove this?

2023-11-06 13:58 UTC, buildguy commented
### :warning: Build finished in 50m 22s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 6 test(s) failed:

<details><summary><b>org.pentaho.di.core.compress.snappy.SnappyCompressionInputStreamTest.testClose</b> (click to expand)</summary><p>

```
[EMPTY_INPUT] Cannot decompress empty stream
```

</p></details>

<details><summary><b>org.pentaho.di.core.compress.snappy.SnappyCompressionInputStreamTest.testCtor</b> (click to expand)</summary><p>

```
[EMPTY_INPUT] Cannot decompress empty stream
```

</p></details>

<details><summary><b>org.pentaho.di.core.compress.snappy.SnappyCompressionInputStreamTest.testRead</b> (click to expand)</summary><p>

```
[EMPTY_INPUT] Cannot decompress empty stream
```

</p></details>

<details><summary><b>org.pentaho.di.core.compress.snappy.SnappyCompressionInputStreamTest.getCompressionProvider</b> (click to expand)</summary><p>

```
[EMPTY_INPUT] Cannot decompress empty stream
```

</p></details>

<details><summary><b>org.pentaho.di.core.compress.snappy.SnappyCompressionInputStreamTest.testNextEntry</b> (click to expand)</summary><p>

```
[EMPTY_INPUT] Cannot decompress empty stream
```

</p></details>

<details><summary><b>org.pentaho.di.core.compress.snappy.SnappyCompressionProviderTest.testCreateInputStream</b> (click to expand)</summary><p>

```
[EMPTY_INPUT] Cannot decompress empty stream
```

</p></details>

  
Tests run: **5327**, Failures: **6**, Skipped: **14** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9070/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-02-14 11:52 UTC, smmribeiro commented
This PR is outdated.
Closing.

2024-02-14 11:52 UTC, closed without merging