[BACKLOG-39116] - Code changes for moving job step 'Display msgbox info' from core to plugin.
pentaho/pentaho-kettle pull request #9096
Opened 2023-11-08 10:57 UTC by nawaz34-hitachivantara

2023-11-08 11:36 UTC, buildguy commented
### :white_check_mark: Build finished in 39m 32s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/plugins,engine,plugins,plugins/msg-box-info,plugins/msg-box-info/assemblies,plugins/msg-box-info/assemblies/plugin,plugins/msg-box-info/impl,plugins/msg-box-info/ui,ui
```
---
:ok_hand: All tests passed!
 
Tests run: **5185**, Failures: **0**, Skipped: **11** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9096/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-11-09 14:19 UTC, peterrinehart requested changes

2023-11-09 14:19 UTC, peterrinehart commented on plugins/msg-box-info/pom.xml
> +    <org.eclipse.swt.version>4.6</org.eclipse.swt.version>
This version should be referenced from the kettle parent pom, not directly in this plugin.  We only want to have one place to update this version in the future, not in every different plugin.

2023-11-09 14:19 UTC, peterrinehart commented on plugins/msg-box-info/pom.xml
> +    <jface.version>3.3.0-I20070606-0010</jface.version>
We probably want to move this version into the kettle parent pom and remove it from this pom and the ui pom.

2023-11-10 10:29 UTC, closed without merging