[BACKLOG-40165] Introduce SMB VFS support
pentaho/pentaho-kettle pull request #9247
Opened 2024-03-26 20:17 UTC by tkafalas

2024-03-26 20:31 UTC, buildguy commented
### :x: Build failed in 13m 57s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -Djs.no.sandbox -pl core,engine
```
---
:ok_hand: All tests passed!
 
Tests run: **1908**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9247/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-03-26 20:48 UTC, buildguy commented
### :x: Build failed in 13m 38s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -Djs.no.sandbox -pl core,engine
```
---
:ok_hand: All tests passed!
 
Tests run: **1527**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9247/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-03-27 21:22 UTC, buildguy commented
### :x: Build failed in 13m 50s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -Djs.no.sandbox -pl core,engine
```
---
:ok_hand: All tests passed!
 
Tests run: **1527**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9247/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-03-28 13:09 UTC, buildguy commented
### :x: Build failed in 18m 58s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -Djs.no.sandbox -pl core,engine
```
---
:ok_hand: All tests passed!
 
Tests run: **1624**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9247/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-03-28 18:08 UTC, buildguy commented
### :x: Build failed in 16m 20s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -Djs.no.sandbox -pl core,engine
```
---
:ok_hand: All tests passed!
 
Tests run: **1652**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9247/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-03-28 18:22 UTC, buildguy commented
### :x: Build failed in 14m 13s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -Djs.no.sandbox -pl core,engine
```
---
:ok_hand: All tests passed!
 
Tests run: **1537**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9247/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-03-28 19:58 UTC, peterrinehart requested changes

2024-03-28 19:58 UTC, peterrinehart commented on core/src/main/java/org/pentaho/di/core/vfs/KettleVFS.java
> +      Pattern pattern = Pattern.compile( "^[Ss][Mm][Bb]://[/]?([^:/]+)(?::([^/]+))?.*$" );
We should compile this pattern only once and reuse it in subsequent calls.

2024-03-28 19:58 UTC, peterrinehart commented on core/src/main/java/org/pentaho/di/connections/vfs/provider/ConnectionFileSystem.java
> +        url = abstractFileName.getURI().replaceFirst( "pvfs:", "smb:" );
Can we store smb: in some common constant and use it instead of having the string re-typed in every class that uses it?

2024-03-28 21:07 UTC, buildguy commented
### :x: Build failed in 15m 55s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -Djs.no.sandbox -pl core,engine
```
---
:ok_hand: All tests passed!
 
Tests run: **1705**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9247/7/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-03-29 13:09 UTC, buildguy commented
### :x: Build failed in 4s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -Djs.no.sandbox
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
Could not find credentials matching jfrog-pentaho-service-cicd
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

2024-03-29 13:46 UTC, buildguy commented
### :x: Build failed in 16m 39s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -Djs.no.sandbox -pl core,engine
```
---
:ok_hand: All tests passed!
 
Tests run: **1455**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9247/9/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-03-31 12:56 UTC, buildguy commented
### :x: Build failed in 13m 12s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl core,engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3591**, Failures: **0**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9247/10/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-04-01 09:05 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-04-01 09:05 UTC, buildguy commented
### :white_check_mark: Build finished in 27m 15s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl core,engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3591**, Failures: **0**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9247/11/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-04-01 14:13 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-04-01 14:13 UTC, buildguy commented
### :white_check_mark: Build finished in 29m 57s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
core,engine,plugins/file-open-save-new/core
```
---
:ok_hand: All tests passed!
 
Tests run: **3629**, Failures: **0**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9247/12/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-04-01 15:33 UTC, peterrinehart approved these changes

2024-04-01 15:34 UTC, merged