[PDI-19734] - Jobs getting failed due to same name in sub job & sub transformation in v9.3: org.pentaho.di.job.JobMeta cannot be cast to org.pentaho.di.trans.TransMeta
pentaho/pentaho-kettle pull request #9271
Opened 2024-04-11 15:25 UTC by andreramos89

@smmribeiro 
@renato-s

2024-04-11 15:56 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-04-11 15:56 UTC, buildguy commented
### :warning: Build finished in 30m 23s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl engine
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.di.base.MetaFileCacheImplTest.logCacheSummaryTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.base.MetaFileCacheImplTest.cacheMetaAndGetCacheTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **2322**, Failures: **2**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9271/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-04-11 16:53 UTC, buildguy commented
### :x: Build failed in 1m 18s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

2024-04-11 17:14 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-04-11 17:17 UTC, smmribeiro requested changes

2024-04-11 17:17 UTC, smmribeiro commented on engine/src/main/java/org/pentaho/di/job/entries/job/JobEntryJob.java
> +        || ( execPerRow && rows.isEmpty() && iteration <= rows.size() && shouldConsiderOldBehaviourForEveryInputRow() ) ) {
Please remove these changes as they are for the other issue.

2024-04-11 17:17 UTC, smmribeiro commented on engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java
> +        // after processing the last row. Otherwise if iteration == rows.size() indicates that we processed already the last row and just need to break from the loop
Please remove these changes as they are for the other issue.

2024-04-11 17:17 UTC, smmribeiro commented on engine/src/main/java/org/pentaho/di/base/MetaFileCacheImpl.java
> +    String keyNormalized = key.endsWith( ".kjb" ) ? key : key + ".kjb";
Strings ".kjb" and ".ktr" should be extracted to a constant to avoid multiple instantiations.

2024-04-11 19:13 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-04-11 19:13 UTC, buildguy commented
### :warning: Build finished in 24m 42s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl engine
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.di.base.MetaFileCacheImplTest.logCacheSummaryTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.base.MetaFileCacheImplTest.cacheMetaAndGetCacheTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **2322**, Failures: **2**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9271/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-04-11 19:31 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-04-11 19:31 UTC, buildguy commented
### :warning: Build finished in 17m 26s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl engine
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.di.base.MetaFileCacheImplTest.logCacheSummaryTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.base.MetaFileCacheImplTest.cacheMetaAndGetCacheTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **2322**, Failures: **2**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9271/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-04-17 10:07 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-04-17 10:07 UTC, buildguy commented
### :warning: Build finished in 24m 22s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl engine
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.di.base.MetaFileCacheImplTest.logCacheSummaryTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.base.MetaFileCacheImplTest.cacheMetaAndGetCacheTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **2322**, Failures: **2**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9271/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-04-17 10:55 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-04-17 10:55 UTC, buildguy commented
### :white_check_mark: Build finished in 25m 47s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **2322**, Failures: **0**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9271/7/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-04-17 14:40 UTC, smmribeiro approved these changes
Looks good.

2024-04-17 14:41 UTC, merged