[PRD-6159] - upgrading the apache poi library to 5.2.5 version for Ex…
pentaho/pentaho-kettle pull request #9398
Opened 2024-06-03 16:24 UTC by lsaikrishna89

…cel writer step

2024-06-03 16:42 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-06-03 16:42 UTC, buildguy commented
### :warning: Build finished in 17m 33s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
plugins/excel/core,plugins/xml
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 79 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_NoHeader_StartRow12</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_NoHeader_InlinedStrings_Streaming</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testXLSX</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testXLSXStream</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_MultipleSheets_Header_StartRow0</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_MultipleSheets_Header_StartRowX</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_NoHeader_InlinedStrings_NoStreaming</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_Header_InlinedStrings_Streaming</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_Header_StartRow0</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_Header_StartRow5</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_MultipleSheets_NoHeader_StartRow0</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_MultipleSheets_NoHeader_StartRowX</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testXLSXCompressionRatioIsBig</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_NoHeader_SharedStrings_Streaming</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_Header_InlinedStrings_NoStreaming</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_Header_SharedStrings_Streaming</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_NoHeader_SharedStrings_NoStreaming</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_Header_SharedStrings_NoStreaming</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_NoHeader_StartRow0</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_NoHeader_StartRow5</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_Header_StartRow12</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheetTest.testNullDateCell</b> (click to expand)</summary><p>

```
'org.apache.xmlbeans.XmlOptions org.apache.xmlbeans.XmlOptions.setUseDefaultNamespace(boolean)'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheetTest.testEmptySheet_row0</b> (click to expand)</summary><p>

```
Unexpected exception, expected<ja [...]

2024-06-04 06:22 UTC, buildguy commented
### :x: Build failed in 1m 34s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
docker login failed
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

2024-06-04 07:49 UTC, buildguy commented
### :x: Build failed in 44m 58s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 81 test(s) failed:

<details><summary><b>org.pentaho.di.core.xml.XMLHandlerUnitTest.addTagValueBinary</b> (click to expand)</summary><p>

```
expected:<...ytedata>H4sIAAAAAAAA[/w]tJLS5RcEksSQQAL4PL8Q...> but was:<...ytedata>H4sIAAAAAAAA[AA]tJLS5RcEksSQQAL4PL8Q...>
```

</p></details>

<details><summary><b>org.pentaho.ui.database.event.FragmentHandlerTest.org.pentaho.ui.database.event.FragmentHandlerTest</b> (click to expand)</summary><p>

```
No more handles [gtk_init_check() failed]
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.fieldsplitter.FieldSplitterTest.testSplitFields</b> (click to expand)</summary><p>

```
Output row is of an unexpected length expected:<4> but was:<3>
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.aggregaterows.AggregateRowsTest.testProcessRow</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.creditcardvalidator.CreditCardValidatorMetaTest.testLoadSave</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.edi2xml.Edi2XmlMetaTest.testStepMeta</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.mailinput.MailInputMetaTest.testSerialization</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.getrepositorynames.GetRepositoryNamesMetaTest.testRoundTrip</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.googleanalytics.GaInputStepMetaTest.testSerialization</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.gpload.GPLoadMetaTest.testRoundTrip</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.infobrightoutput.InfobrightLoaderMetaTest.testSerialization</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputMetaLoadSaveTest.testLoadSave</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testDefaultLeafToNullChangedToFalse_NoNullInOutput</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testSingleObjPred</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testExpressionWithLegacyModeEnable</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testChildDot</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testChildBracketsNDots</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testDualExpMismatchError</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testBfsMatchOrder</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testDefaultLeafToNullTrue_NullsInOutput</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testExpressionWithLegacyModeDisable</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testBadInput</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testAttrFilter</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testIndex</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testNullProp</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testJsonInputPathResolutionSuccess</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testObjectOut</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testSmallDoubles</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testChildBrackets</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testArrayOut</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testRemoveSourceField</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testRepeatFieldSingleObj</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testZeroSizeFile</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testUrlInput</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testBicycleAsterisk</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testIndexList</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput [...]

2024-06-04 09:10 UTC, buildguy commented
### :x: Build failed in 43m 51s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 81 test(s) failed:

<details><summary><b>org.pentaho.di.core.xml.XMLHandlerUnitTest.addTagValueBinary</b> (click to expand)</summary><p>

```
expected:<...ytedata>H4sIAAAAAAAA[/w]tJLS5RcEksSQQAL4PL8Q...> but was:<...ytedata>H4sIAAAAAAAA[AA]tJLS5RcEksSQQAL4PL8Q...>
```

</p></details>

<details><summary><b>org.pentaho.ui.database.event.FragmentHandlerTest.org.pentaho.ui.database.event.FragmentHandlerTest</b> (click to expand)</summary><p>

```
No more handles [gtk_init_check() failed]
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.fieldsplitter.FieldSplitterTest.testSplitFields</b> (click to expand)</summary><p>

```
Output row is of an unexpected length expected:<4> but was:<3>
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.aggregaterows.AggregateRowsTest.testProcessRow</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.creditcardvalidator.CreditCardValidatorMetaTest.testLoadSave</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.edi2xml.Edi2XmlMetaTest.testStepMeta</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.mailinput.MailInputMetaTest.testSerialization</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.getrepositorynames.GetRepositoryNamesMetaTest.testRoundTrip</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.googleanalytics.GaInputStepMetaTest.testSerialization</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.gpload.GPLoadMetaTest.testRoundTrip</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.infobrightoutput.InfobrightLoaderMetaTest.testSerialization</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputMetaLoadSaveTest.testLoadSave</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testDefaultLeafToNullChangedToFalse_NoNullInOutput</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testSingleObjPred</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testExpressionWithLegacyModeEnable</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testChildDot</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testChildBracketsNDots</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testDualExpMismatchError</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testBfsMatchOrder</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testDefaultLeafToNullTrue_NullsInOutput</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testExpressionWithLegacyModeDisable</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testBadInput</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testAttrFilter</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testIndex</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testNullProp</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testJsonInputPathResolutionSuccess</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testObjectOut</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testSmallDoubles</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testChildBrackets</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testArrayOut</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testRemoveSourceField</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testRepeatFieldSingleObj</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testZeroSizeFile</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testUrlInput</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testBicycleAsterisk</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testIndexList</b> (click to expand)</summary><p>

```
'org.mockito.stubbing.LenientStubber org.mockito.Mockito.lenient()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput [...]

2024-06-04 10:50 UTC, buildguy commented
<div align='center'>

[![🚨 Frogbot scanned this pull request and found the below:](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/vulnerabilitiesBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>


## 📦 Vulnerable Dependencies
### ✍️ Summary
<div align='center'>

| SEVERITY                | DIRECT DEPENDENCIES                  | IMPACTED DEPENDENCY                  | FIXED VERSIONS                  | CVES                  |
| :---------------------: | :-----------------------------------: | :-----------------------------------: | :-----------------------------------: | :-----------------------------------: |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableCriticalSeverity.png)<br>Critical | org.apache.activemq:artemis-junit:2.5.0 | org.apache.activemq:artemis-server 2.5.0 | [2.31.2] | CVE-2023-46604 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableCriticalSeverity.png)<br>Critical | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.44.Final] | CVE-2019-20444 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableCriticalSeverity.png)<br>Critical | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.44.Final] | CVE-2019-20445 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec 4.1.22.Final | [4.1.68.Final] | CVE-2021-37136 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | org.apache.activemq:artemis-core-client 2.5.0 | [2.19.1] | CVE-2022-23913 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-handler 4.1.22.Final | [4.1.46] | CVE-2020-11612 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec 4.1.22.Final | [4.1.68.Final] | CVE-2021-37137 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.71.Final] | CVE-2021-43797 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.108.Final] | CVE-2024-29025 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-junit:2.5.0 | org.apache.activemq:artemis-server 2.5.0 | [2.24.0] | CVE-2022-35278 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.59.Final] | CVE-2021-21290 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-handler 4.1.22.Final | [4.1.94.Final] | CVE-2023-34462 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.77.Final] | CVE-2022-24823 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | org.apache.activemq:artemis-core-client 2.5.0 | [2.19.1] | CVE-2021-4040 |

</div>

<details>
<summary> <b>🔬 Research Details</b> </summary>
<br>

<details>
<summary> <b>[ CVE-2023-46604 ] org.apache.activemq:artemis-server 2.5.0</b> </summary>
<br>


**Description:**
[Apache ActiveMQ](https://activemq.apache.org/) is a widely-used open-source message broker written in Java, known for its multi-protocol compatibility. It offers clients the flexibility of choosing from various programming languages and platforms, with support for JavaScript, C, C++, Python, .NET, and others.

[Apache ActiveMQ Artemis](https://activemq.apache.org/components/artemis/) is a next-generation, high-performance message broker, designed as a successor to the classic Apache ActiveMQ, offering improved performance, scalability, and a more modern architecture for messaging applications.

ActiveMQ can broker multiple protocol formats, such as AMQP, STOMP, MQTT, and OpenWire.
The OpenWire implementation in ActiveMQ was discovered to be vulnerable to a deserialization attack, which may lead to remote code execution by unauthenticated network attackers.

The vulnerability is highly likely to be exploited, since it is exploitable by unauthenticated network attackers, in the default ActiveMQ server configuration, by using a public exploit and with no need for target-specific research.

Successful exploitation requires a class on the classpath to be used as a gadget, which can execute arbitrary code simply by instantiating it with a String parameter.

One of the classes shipped in the classic ActiveMQ is `org.springframework.context.support.ClassPathXmlApplicationContext`.
The purpose of `ClassPathXmlApplicationContext` is to retrieve an XML application configuration file via HTTP from a remote location on the network, which is used in the published PoCs to execute arbitrary code.

The Artemis versions also support the OpenWire protocol but does not ship with this gadget class, so exploitation of Artemis has not yet been proven.

The OpenWire transport is enabled by default and listens on TCP port 61616.

**Remediation:**
##### Deployment mitigations

You can switch from using the vulnerable `OpenWire` protocol to another protocol (and adjust the MQTT clients accordingly).

On ActiveMQ (the default Classic project):
In the configuration file `activemq.xml` change the transport connector to one of the following - AMQP / MQTT / STOMP / Websockets.

An example of a vulnerable transport connector:
```
<transportConnector name="tcp" uri="tcp://0.0.0.0:61616"/>
```

An example of non-vulnerable transport connectors:
```
<transportConnector name="amqp" uri="amqp://0.0.0.0:5672"/>
<transportConnector name="stomp" uri="stomp://0.0.0.0:61613"/>
<transportConnector name="mqtt" uri="mqtt://0.0.0.0:1883"/>
<transportConnector name="ws" uri="ws://0.0.0.0:61614"/>
```

On ActiveMQ Artemis:
In the configuration file `broker.xml` change the protocol to one of the following - CORE / AMQP / MQTT / STOMP.

Example of a vulnerable configuration where all protocols are enabled including OpenWire:
```
<acceptors>
   <acceptor>tcp://localhost: [...]

2024-06-04 10:59 UTC, buildguy commented
<div align='center'>

[![🚨 Frogbot scanned this pull request and found the below:](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/vulnerabilitiesBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>


## 📦 Vulnerable Dependencies
### ✍️ Summary
<div align='center'>

| SEVERITY                | DIRECT DEPENDENCIES                  | IMPACTED DEPENDENCY                  | FIXED VERSIONS                  | CVES                  |
| :---------------------: | :-----------------------------------: | :-----------------------------------: | :-----------------------------------: | :-----------------------------------: |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableCriticalSeverity.png)<br>Critical | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.44.Final] | CVE-2019-20444 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableCriticalSeverity.png)<br>Critical | org.apache.activemq:artemis-junit:2.5.0 | org.apache.activemq:artemis-server 2.5.0 | [2.31.2] | CVE-2023-46604 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableCriticalSeverity.png)<br>Critical | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.44.Final] | CVE-2019-20445 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | org.apache.activemq:artemis-core-client 2.5.0 | [2.19.1] | CVE-2022-23913 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec 4.1.22.Final | [4.1.68.Final] | CVE-2021-37137 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec 4.1.22.Final | [4.1.68.Final] | CVE-2021-37136 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-handler 4.1.22.Final | [4.1.46] | CVE-2020-11612 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.77.Final] | CVE-2022-24823 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.59.Final] | CVE-2021-21290 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-junit:2.5.0 | org.apache.activemq:artemis-server 2.5.0 | [2.24.0] | CVE-2022-35278 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.71.Final] | CVE-2021-43797 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-handler 4.1.22.Final | [4.1.94.Final] | CVE-2023-34462 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.108.Final] | CVE-2024-29025 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | org.apache.activemq:artemis-core-client 2.5.0 | [2.19.1] | CVE-2021-4040 |

</div>

<details>
<summary> <b>🔬 Research Details</b> </summary>
<br>

<details>
<summary> <b>[ CVE-2019-20444 ] io.netty:netty-codec-http 4.1.22.Final</b> </summary>
<br>


**Description:**
HttpObjectDecoder.java in Netty before 4.1.44 allows an HTTP header that lacks a colon, which might be interpreted as a separate header with an incorrect syntax, or might be interpreted as an "invalid fold."

</details>

<details>
<summary> <b>[ CVE-2023-46604 ] org.apache.activemq:artemis-server 2.5.0</b> </summary>
<br>


**Description:**
[Apache ActiveMQ](https://activemq.apache.org/) is a widely-used open-source message broker written in Java, known for its multi-protocol compatibility. It offers clients the flexibility of choosing from various programming languages and platforms, with support for JavaScript, C, C++, Python, .NET, and others.

[Apache ActiveMQ Artemis](https://activemq.apache.org/components/artemis/) is a next-generation, high-performance message broker, designed as a successor to the classic Apache ActiveMQ, offering improved performance, scalability, and a more modern architecture for messaging applications.

ActiveMQ can broker multiple protocol formats, such as AMQP, STOMP, MQTT, and OpenWire.
The OpenWire implementation in ActiveMQ was discovered to be vulnerable to a deserialization attack, which may lead to remote code execution by unauthenticated network attackers.

The vulnerability is highly likely to be exploited, since it is exploitable by unauthenticated network attackers, in the default ActiveMQ server configuration, by using a public exploit and with no need for target-specific research.

Successful exploitation requires a class on the classpath to be used as a gadget, which can execute arbitrary code simply by instantiating it with a String parameter.

One of the classes shipped in the classic ActiveMQ is `org.springframework.context.support.ClassPathXmlApplicationContext`.
The purpose of `ClassPathXmlApplicationContext` is to retrieve an XML application configuration file via HTTP from a remote location on the network, which is used in the published PoCs to execute arbitrary code.

The Artemis versions also support the OpenWire protocol but does not ship with this gadget class, so exploitation of Artemis has not yet been proven.

The OpenWire transport is enabled by default and listens on TCP port 61616.

**Remediation:**
##### Deployment mitigations

You can switch from using the vulnerable `OpenWire` protocol to another protocol (and adjust the MQTT clients accordingly).

On ActiveMQ (the default Classic project):
In the configuration file `activemq.xml` change the transport connector to one of the following - AMQP / MQTT / STOMP / Websockets.

An example of a vulnerable transport connector:
```
<transportConnector name="tcp" uri="tcp://0.0.0.0:61616"/>
```

An example of non-vulnerable transport connectors:
```
<transportConnector name="amqp" uri="amqp://0.0.0.0:5672"/>
<transportConnector name="stomp" uri="stomp://0.0.0.0:61613"/>
<transportConnector name="mqtt" uri="mqtt://0.0.0.0 [...]

2024-06-04 10:59 UTC, buildguy commented
### :x: Build failed in 47m 9s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 135 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_NoHeader_StartRow12</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_NoHeader_InlinedStrings_Streaming</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testXLSX</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testXLSXStream</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_MultipleSheets_Header_StartRow0</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_MultipleSheets_Header_StartRowX</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_NoHeader_InlinedStrings_NoStreaming</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_Header_InlinedStrings_Streaming</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_Header_StartRow0</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_Header_StartRow5</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_MultipleSheets_NoHeader_StartRow0</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_MultipleSheets_NoHeader_StartRowX</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testXLSXCompressionRatioIsBig</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_NoHeader_SharedStrings_Streaming</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_Header_InlinedStrings_NoStreaming</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_Header_SharedStrings_Streaming</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_NoHeader_SharedStrings_NoStreaming</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_Header_SharedStrings_NoStreaming</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_NoHeader_StartRow0</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_NoHeader_StartRow5</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_Header_StartRow12</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheetTest.testNullDateCell</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheetTest.testReadCells</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheetTest.testReadRowRA</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheetTest.testReadData</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheetTest.testReadSameRow</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheetTest.testReadEmptyRow</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheetTest.testInlineString</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheetTest.testNoUsedRangeSpecified</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterFullTest.testCreateFolder</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterFullTest.testNullsEmptyStr</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterFullTest.testDataValidationExtension</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterFullTest.testWriteStreamingTemplate</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterFullTest.testWriteStreamingTemplateOutFields</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterFullTest.testNullsBlank</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.testWriteUsingTemplateWithFormatting</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.testValueString</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.testValueBigNumber</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.test_Xlsx_Stream_NoTemplate</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.testValueInteger</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.testValueInternetAddress</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.d [...]

2024-06-04 11:34 UTC, buildguy commented
<div align='center'>

[![🚨 Frogbot scanned this pull request and found the below:](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/vulnerabilitiesBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>


## 📦 Vulnerable Dependencies
### ✍️ Summary
<div align='center'>

| SEVERITY                | DIRECT DEPENDENCIES                  | IMPACTED DEPENDENCY                  | FIXED VERSIONS                  | CVES                  |
| :---------------------: | :-----------------------------------: | :-----------------------------------: | :-----------------------------------: | :-----------------------------------: |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableCriticalSeverity.png)<br>Critical | org.apache.activemq:artemis-junit:2.5.0 | org.apache.activemq:artemis-server 2.5.0 | [2.31.2] | CVE-2023-46604 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableCriticalSeverity.png)<br>Critical | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.44.Final] | CVE-2019-20444 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableCriticalSeverity.png)<br>Critical | org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT<br>org.apache.activemq:artemis-jms-client-osgi:2.5.0 | io.netty:netty-codec-http 4.1.22.Final | [4.1.44.Final] | CVE-2019-20445 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec 4.1.22.Final | [4.1.68.Final] | CVE-2021-37136 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec 4.1.22.Final | [4.1.68.Final] | CVE-2021-37137 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | org.apache.activemq:artemis-core-client 2.5.0 | [2.19.1] | CVE-2022-23913 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-handler 4.1.22.Final | [4.1.46] | CVE-2020-11612 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | org.apache.activemq:artemis-core-client 2.5.0 | [2.19.1] | CVE-2021-4040 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.77.Final] | CVE-2022-24823 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT<br>org.apache.activemq:artemis-jms-client-osgi:2.5.0 | io.netty:netty-codec-http 4.1.22.Final | [4.1.108.Final] | CVE-2024-29025 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.71.Final] | CVE-2021-43797 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-handler 4.1.22.Final | [4.1.94.Final] | CVE-2023-34462 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.59.Final] | CVE-2021-21290 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-junit:2.5.0 | org.apache.activemq:artemis-server 2.5.0 | [2.24.0] | CVE-2022-35278 |

</div>

<details>
<summary> <b>🔬 Research Details</b> </summary>
<br>

<details>
<summary> <b>[ CVE-2023-46604 ] org.apache.activemq:artemis-server 2.5.0</b> </summary>
<br>


**Description:**
[Apache ActiveMQ](https://activemq.apache.org/) is a widely-used open-source message broker written in Java, known for its multi-protocol compatibility. It offers clients the flexibility of choosing from various programming languages and platforms, with support for JavaScript, C, C++, Python, .NET, and others.

[Apache ActiveMQ Artemis](https://activemq.apache.org/components/artemis/) is a next-generation, high-performance message broker, designed as a successor to the classic Apache ActiveMQ, offering improved performance, scalability, and a more modern architecture for messaging applications.

ActiveMQ can broker multiple protocol formats, such as AMQP, STOMP, MQTT, and OpenWire.
The OpenWire implementation in ActiveMQ was discovered to be vulnerable to a deserialization attack, which may lead to remote code execution by unauthenticated network attackers.

The vulnerability is highly likely to be exploited, since it is exploitable by unauthenticated network attackers, in the default ActiveMQ server configuration, by using a public exploit and with no need for target-specific research.

Successful exploitation requires a class on the classpath to be used as a gadget, which can execute arbitrary code simply by instantiating it with a String parameter.

One of the classes shipped in the classic ActiveMQ is `org.springframework.context.support.ClassPathXmlApplicationContext`.
The purpose of `ClassPathXmlApplicationContext` is to retrieve an XML application configuration file via HTTP from a remote location on the network, which is used in the published PoCs to execute arbitrary code.

The Artemis versions also support the OpenWire protocol but does not ship with this gadget class, so exploitation of Artemis has not yet been proven.

The OpenWire transport is enabled by default and listens on TCP port 61616.

**Remediation:**
##### Deployment mitigations

You can switch from using the vulnerable `OpenWire` protocol to another protocol (and adjust the MQTT clients accordingly).

On ActiveMQ (the default Classic project):
In the configuration file `activemq.xml` change the transport connector to one of the following - AMQP / MQTT / STOMP / Websockets.

An example of a vulnerable transport connector:
```
<transportConnector name="tcp" uri="tcp://0.0.0.0:61616"/>
```

An example of non-vulnerable transport connectors:
```
<transportConnector name="amqp" uri="amqp://0.0.0.0:5672"/>
<transportConnector name="stomp" uri="stomp://0.0.0.0:61613"/>
<transportConnector name="mqtt" uri="mqtt://0.0.0.0:1883"/>
<transportConnector name="ws" uri="ws://0.0.0.0:61614"/>
```

On ActiveMQ Artemis:
In the configuration file `broker.xml` change the protocol to one of the following - CORE / AMQP / MQTT / STOMP.

Example of a vulnerable configuration where all protocols are enabled including OpenWire:
```
<acceptors>
   <acceptor>tcp://localhost: [...]

2024-06-04 11:39 UTC, buildguy commented
### :x: Build failed in 40m 19s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 135 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_NoHeader_StartRow12</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_NoHeader_InlinedStrings_Streaming</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testXLSX</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testXLSXStream</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_MultipleSheets_Header_StartRow0</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_MultipleSheets_Header_StartRowX</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_NoHeader_InlinedStrings_NoStreaming</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_Header_InlinedStrings_Streaming</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_Header_StartRow0</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_Header_StartRow5</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_MultipleSheets_NoHeader_StartRow0</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_MultipleSheets_NoHeader_StartRowX</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testXLSXCompressionRatioIsBig</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_NoHeader_SharedStrings_Streaming</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_Header_InlinedStrings_NoStreaming</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_Header_SharedStrings_Streaming</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_NoHeader_SharedStrings_NoStreaming</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_Header_SharedStrings_NoStreaming</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_NoHeader_StartRow0</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_NoHeader_StartRow5</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_Header_StartRow12</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheetTest.testNullDateCell</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheetTest.testReadCells</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheetTest.testReadRowRA</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheetTest.testReadData</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheetTest.testReadSameRow</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheetTest.testReadEmptyRow</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheetTest.testInlineString</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheetTest.testNoUsedRangeSpecified</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterFullTest.testCreateFolder</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterFullTest.testNullsEmptyStr</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterFullTest.testDataValidationExtension</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterFullTest.testWriteStreamingTemplate</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterFullTest.testWriteStreamingTemplateOutFields</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterFullTest.testNullsBlank</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.testWriteUsingTemplateWithFormatting</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.testValueString</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.testValueBigNumber</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.test_Xlsx_Stream_NoTemplate</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.testValueInteger</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.testValueInternetAddress</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho. [...]

2024-06-04 12:33 UTC, buildguy commented
<div align='center'>

[![🚨 Frogbot scanned this pull request and found the below:](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/vulnerabilitiesBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>


## 📦 Vulnerable Dependencies
### ✍️ Summary
<div align='center'>

| SEVERITY                | DIRECT DEPENDENCIES                  | IMPACTED DEPENDENCY                  | FIXED VERSIONS                  | CVES                  |
| :---------------------: | :-----------------------------------: | :-----------------------------------: | :-----------------------------------: | :-----------------------------------: |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableCriticalSeverity.png)<br>Critical | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.44.Final] | CVE-2019-20445 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableCriticalSeverity.png)<br>Critical | org.apache.activemq:artemis-junit:2.5.0 | org.apache.activemq:artemis-server 2.5.0 | [2.31.2] | CVE-2023-46604 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableCriticalSeverity.png)<br>Critical | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.44.Final] | CVE-2019-20444 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-handler 4.1.22.Final | [4.1.46] | CVE-2020-11612 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | org.apache.activemq:artemis-core-client 2.5.0 | [2.19.1] | CVE-2022-23913 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec 4.1.22.Final | [4.1.68.Final] | CVE-2021-37136 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec 4.1.22.Final | [4.1.68.Final] | CVE-2021-37137 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT<br>org.apache.activemq:artemis-jms-client-osgi:2.5.0 | io.netty:netty-codec-http 4.1.22.Final | [4.1.71.Final] | CVE-2021-43797 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.77.Final] | CVE-2022-24823 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.59.Final] | CVE-2021-21290 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-handler 4.1.22.Final | [4.1.94.Final] | CVE-2023-34462 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-junit:2.5.0 | org.apache.activemq:artemis-server 2.5.0 | [2.24.0] | CVE-2022-35278 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.108.Final] | CVE-2024-29025 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | org.apache.activemq:artemis-core-client 2.5.0 | [2.19.1] | CVE-2021-4040 |

</div>

<details>
<summary> <b>🔬 Research Details</b> </summary>
<br>

<details>
<summary> <b>[ CVE-2019-20445 ] io.netty:netty-codec-http 4.1.22.Final</b> </summary>
<br>


**Description:**
HttpObjectDecoder.java in Netty before 4.1.44 allows a Content-Length header to be accompanied by a second Content-Length header, or by a Transfer-Encoding header.

</details>

<details>
<summary> <b>[ CVE-2023-46604 ] org.apache.activemq:artemis-server 2.5.0</b> </summary>
<br>


**Description:**
[Apache ActiveMQ](https://activemq.apache.org/) is a widely-used open-source message broker written in Java, known for its multi-protocol compatibility. It offers clients the flexibility of choosing from various programming languages and platforms, with support for JavaScript, C, C++, Python, .NET, and others.

[Apache ActiveMQ Artemis](https://activemq.apache.org/components/artemis/) is a next-generation, high-performance message broker, designed as a successor to the classic Apache ActiveMQ, offering improved performance, scalability, and a more modern architecture for messaging applications.

ActiveMQ can broker multiple protocol formats, such as AMQP, STOMP, MQTT, and OpenWire.
The OpenWire implementation in ActiveMQ was discovered to be vulnerable to a deserialization attack, which may lead to remote code execution by unauthenticated network attackers.

The vulnerability is highly likely to be exploited, since it is exploitable by unauthenticated network attackers, in the default ActiveMQ server configuration, by using a public exploit and with no need for target-specific research.

Successful exploitation requires a class on the classpath to be used as a gadget, which can execute arbitrary code simply by instantiating it with a String parameter.

One of the classes shipped in the classic ActiveMQ is `org.springframework.context.support.ClassPathXmlApplicationContext`.
The purpose of `ClassPathXmlApplicationContext` is to retrieve an XML application configuration file via HTTP from a remote location on the network, which is used in the published PoCs to execute arbitrary code.

The Artemis versions also support the OpenWire protocol but does not ship with this gadget class, so exploitation of Artemis has not yet been proven.

The OpenWire transport is enabled by default and listens on TCP port 61616.

**Remediation:**
##### Deployment mitigations

You can switch from using the vulnerable `OpenWire` protocol to another protocol (and adjust the MQTT clients accordingly).

On ActiveMQ (the default Classic project):
In the configuration file `activemq.xml` change the transport connector to one of the following - AMQP / MQTT / STOMP / Websockets.

An example of a vulnerable transport connector:
```
<transportConnector name="tcp" uri="tcp://0.0.0.0:61616"/>
```

An example of non-vulnerable transport connectors:
```
<transportConnector name="amqp" uri="amqp://0.0.0.0:5672"/>
<transportConnector name="stomp" uri="stomp://0.0.0.0:61613"/>
<transportConnector name="mqtt" uri="mqtt://0.0.0.0:1883"/>
<transportConnector name="ws" uri=" [...]

2024-06-04 12:47 UTC, buildguy commented
### :x: Build failed in 51m 1s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 135 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_NoHeader_StartRow12</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_NoHeader_InlinedStrings_Streaming</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testXLSX</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testXLSXStream</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_MultipleSheets_Header_StartRow0</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_MultipleSheets_Header_StartRowX</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_NoHeader_InlinedStrings_NoStreaming</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_Header_InlinedStrings_Streaming</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_Header_StartRow0</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_Header_StartRow5</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_MultipleSheets_NoHeader_StartRow0</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_MultipleSheets_NoHeader_StartRowX</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testXLSXCompressionRatioIsBig</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_NoHeader_SharedStrings_Streaming</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_Header_InlinedStrings_NoStreaming</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_Header_SharedStrings_Streaming</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_NoHeader_SharedStrings_NoStreaming</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_Header_SharedStrings_NoStreaming</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_NoHeader_StartRow0</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_NoHeader_StartRow5</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_Header_StartRow12</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheetTest.testNullDateCell</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheetTest.testReadCells</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheetTest.testReadRowRA</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheetTest.testReadData</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheetTest.testReadSameRow</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheetTest.testReadEmptyRow</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheetTest.testInlineString</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheetTest.testNoUsedRangeSpecified</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterFullTest.testCreateFolder</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterFullTest.testNullsEmptyStr</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterFullTest.testDataValidationExtension</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterFullTest.testWriteStreamingTemplate</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterFullTest.testWriteStreamingTemplateOutFields</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterFullTest.testNullsBlank</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.testWriteUsingTemplateWithFormatting</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.testValueString</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.testValueBigNumber</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.test_Xlsx_Stream_NoTemplate</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.testValueInteger</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.testValueInternetAddress</b> (click to expand)</summary><p>

```
Factory
```

</p></details>

<details><summary><b>org.pentaho.d [...]

2024-06-04 13:16 UTC, lucboudreau requested changes
XmlBeans, Apache POI and Commons-IO are flagged for an update in the tickets below. Any chance we can do the upgrade across the platform through the maven parent pom isntead of jsut this project?

https://hv-eng.atlassian.net/browse/PPP-4899
https://hv-eng.atlassian.net/issues/PPP-4948
https://hv-eng.atlassian.net/issues/PPP-4968

2024-06-04 18:47 UTC, buildguy commented
<div align='center'>

[![🚨 Frogbot scanned this pull request and found the below:](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/vulnerabilitiesBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>


## 📦 Vulnerable Dependencies
### ✍️ Summary
<div align='center'>

| SEVERITY                | DIRECT DEPENDENCIES                  | IMPACTED DEPENDENCY                  | FIXED VERSIONS                  | CVES                  |
| :---------------------: | :-----------------------------------: | :-----------------------------------: | :-----------------------------------: | :-----------------------------------: |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableCriticalSeverity.png)<br>Critical | org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT<br>org.apache.activemq:artemis-jms-client-osgi:2.5.0 | io.netty:netty-codec-http 4.1.22.Final | [4.1.44.Final] | CVE-2019-20445 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableCriticalSeverity.png)<br>Critical | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.44.Final] | CVE-2019-20444 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableCriticalSeverity.png)<br>Critical | org.apache.activemq:artemis-junit:2.5.0 | org.apache.activemq:artemis-server 2.5.0 | [2.31.2] | CVE-2023-46604 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec 4.1.22.Final | [4.1.68.Final] | CVE-2021-37137 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-handler 4.1.22.Final | [4.1.46] | CVE-2020-11612 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec 4.1.22.Final | [4.1.68.Final] | CVE-2021-37136 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | org.apache.activemq:artemis-core-client 2.5.0 | [2.19.1] | CVE-2022-23913 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.59.Final] | CVE-2021-21290 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.71.Final] | CVE-2021-43797 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | org.apache.activemq:artemis-core-client 2.5.0 | [2.19.1] | CVE-2021-4040 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-junit:2.5.0 | org.apache.activemq:artemis-server 2.5.0 | [2.24.0] | CVE-2022-35278 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.108.Final] | CVE-2024-29025 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.77.Final] | CVE-2022-24823 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-handler 4.1.22.Final | [4.1.94.Final] | CVE-2023-34462 |

</div>

<details>
<summary> <b>🔬 Research Details</b> </summary>
<br>

<details>
<summary> <b>[ CVE-2019-20445 ] io.netty:netty-codec-http 4.1.22.Final</b> </summary>
<br>


**Description:**
HttpObjectDecoder.java in Netty before 4.1.44 allows a Content-Length header to be accompanied by a second Content-Length header, or by a Transfer-Encoding header.

</details>

<details>
<summary> <b>[ CVE-2019-20444 ] io.netty:netty-codec-http 4.1.22.Final</b> </summary>
<br>


**Description:**
HttpObjectDecoder.java in Netty before 4.1.44 allows an HTTP header that lacks a colon, which might be interpreted as a separate header with an incorrect syntax, or might be interpreted as an "invalid fold."

</details>

<details>
<summary> <b>[ CVE-2023-46604 ] org.apache.activemq:artemis-server 2.5.0</b> </summary>
<br>


**Description:**
[Apache ActiveMQ](https://activemq.apache.org/) is a widely-used open-source message broker written in Java, known for its multi-protocol compatibility. It offers clients the flexibility of choosing from various programming languages and platforms, with support for JavaScript, C, C++, Python, .NET, and others.

[Apache ActiveMQ Artemis](https://activemq.apache.org/components/artemis/) is a next-generation, high-performance message broker, designed as a successor to the classic Apache ActiveMQ, offering improved performance, scalability, and a more modern architecture for messaging applications.

ActiveMQ can broker multiple protocol formats, such as AMQP, STOMP, MQTT, and OpenWire.
The OpenWire implementation in ActiveMQ was discovered to be vulnerable to a deserialization attack, which may lead to remote code execution by unauthenticated network attackers.

The vulnerability is highly likely to be exploited, since it is exploitable by unauthenticated network attackers, in the default ActiveMQ server configuration, by using a public exploit and with no need for target-specific research.

Successful exploitation requires a class on the classpath to be used as a gadget, which can execute arbitrary code simply by instantiating it with a String parameter.

One of the classes shipped in the classic ActiveMQ is `org.springframework.context.support.ClassPathXmlApplicationContext`.
The purpose of `ClassPathXmlApplicationContext` is to retrieve an XML application configuration file via HTTP from a remote location on the network, which is used in the published PoCs to execute arbitrary code.

The Artemis versions also support the OpenWire protocol but does not ship with this gadget class, so exploitation of Artemis has not yet been proven.

The OpenWire transport is enabled by default and listens on TCP port 61616.

**Remediation:**
##### Deployment mitigations

You can switch from using the vulnerable `OpenWire` protocol to another protocol (and adjust the MQTT clients accordingly).

On ActiveMQ (the default Classic project):
In the configuration file `activemq.xml` change the transport connector to one of the following - AMQP / MQTT / STOMP / Websockets.

An example of a vulnerable transport connector:
 [...]

2024-06-04 18:57 UTC, buildguy commented
<div align='center'>

[![🚨 Frogbot scanned this pull request and found the below:](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/vulnerabilitiesBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>


## 📦 Vulnerable Dependencies
### ✍️ Summary
<div align='center'>

| SEVERITY                | DIRECT DEPENDENCIES                  | IMPACTED DEPENDENCY                  | FIXED VERSIONS                  | CVES                  |
| :---------------------: | :-----------------------------------: | :-----------------------------------: | :-----------------------------------: | :-----------------------------------: |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableCriticalSeverity.png)<br>Critical | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.44.Final] | CVE-2019-20444 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableCriticalSeverity.png)<br>Critical | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.44.Final] | CVE-2019-20445 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableCriticalSeverity.png)<br>Critical | org.apache.activemq:artemis-junit:2.5.0 | org.apache.activemq:artemis-server 2.5.0 | [2.31.2] | CVE-2023-46604 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec 4.1.22.Final | [4.1.68.Final] | CVE-2021-37137 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec 4.1.22.Final | [4.1.68.Final] | CVE-2021-37136 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | org.apache.activemq:artemis-core-client 2.5.0 | [2.19.1] | CVE-2022-23913 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-handler 4.1.22.Final | [4.1.46] | CVE-2020-11612 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | org.apache.activemq:artemis-core-client 2.5.0 | [2.19.1] | CVE-2021-4040 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-handler 4.1.22.Final | [4.1.94.Final] | CVE-2023-34462 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.77.Final] | CVE-2022-24823 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.108.Final] | CVE-2024-29025 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.59.Final] | CVE-2021-21290 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.71.Final] | CVE-2021-43797 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-junit:2.5.0 | org.apache.activemq:artemis-server 2.5.0 | [2.24.0] | CVE-2022-35278 |

</div>

<details>
<summary> <b>🔬 Research Details</b> </summary>
<br>

<details>
<summary> <b>[ CVE-2019-20444 ] io.netty:netty-codec-http 4.1.22.Final</b> </summary>
<br>


**Description:**
HttpObjectDecoder.java in Netty before 4.1.44 allows an HTTP header that lacks a colon, which might be interpreted as a separate header with an incorrect syntax, or might be interpreted as an "invalid fold."

</details>

<details>
<summary> <b>[ CVE-2019-20445 ] io.netty:netty-codec-http 4.1.22.Final</b> </summary>
<br>


**Description:**
HttpObjectDecoder.java in Netty before 4.1.44 allows a Content-Length header to be accompanied by a second Content-Length header, or by a Transfer-Encoding header.

</details>

<details>
<summary> <b>[ CVE-2023-46604 ] org.apache.activemq:artemis-server 2.5.0</b> </summary>
<br>


**Description:**
[Apache ActiveMQ](https://activemq.apache.org/) is a widely-used open-source message broker written in Java, known for its multi-protocol compatibility. It offers clients the flexibility of choosing from various programming languages and platforms, with support for JavaScript, C, C++, Python, .NET, and others.

[Apache ActiveMQ Artemis](https://activemq.apache.org/components/artemis/) is a next-generation, high-performance message broker, designed as a successor to the classic Apache ActiveMQ, offering improved performance, scalability, and a more modern architecture for messaging applications.

ActiveMQ can broker multiple protocol formats, such as AMQP, STOMP, MQTT, and OpenWire.
The OpenWire implementation in ActiveMQ was discovered to be vulnerable to a deserialization attack, which may lead to remote code execution by unauthenticated network attackers.

The vulnerability is highly likely to be exploited, since it is exploitable by unauthenticated network attackers, in the default ActiveMQ server configuration, by using a public exploit and with no need for target-specific research.

Successful exploitation requires a class on the classpath to be used as a gadget, which can execute arbitrary code simply by instantiating it with a String parameter.

One of the classes shipped in the classic ActiveMQ is `org.springframework.context.support.ClassPathXmlApplicationContext`.
The purpose of `ClassPathXmlApplicationContext` is to retrieve an XML application configuration file via HTTP from a remote location on the network, which is used in the published PoCs to execute arbitrary code.

The Artemis versions also support the OpenWire protocol but does not ship with this gadget class, so exploitation of Artemis has not yet been proven.

The OpenWire transport is enabled by default and listens on TCP port 61616.

**Remediation:**
##### Deployment mitigations

You can switch from using the vulnerable `OpenWire` protocol to another protocol (and adjust the MQTT clients accordingly).

On ActiveMQ (the default Classic project):
In the configuration file `activemq.xml` change the transport connector to one of the following - AMQP / MQTT / STOMP / Websockets.

An example of a vulnerable transport connector:
 [...]

2024-06-04 18:57 UTC, buildguy commented
### :x: Build failed in 48m 22s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 158 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.test_Xls_Template</b> (click to expand)</summary><p>

```
'org.apache.commons.io.input.UnsynchronizedByteArrayInputStream$Builder org.apache.commons.io.input.UnsynchronizedByteArrayInputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.test_Xls_Template</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.test_Xls_NoTemplate</b> (click to expand)</summary><p>

```
'org.apache.commons.io.input.UnsynchronizedByteArrayInputStream$Builder org.apache.commons.io.input.UnsynchronizedByteArrayInputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.test_Xls_NoTemplate</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.testProtectSheet</b> (click to expand)</summary><p>

```
'org.apache.commons.io.input.UnsynchronizedByteArrayInputStream$Builder org.apache.commons.io.input.UnsynchronizedByteArrayInputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.testProtectSheet</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.testMaxSheetNameLength</b> (click to expand)</summary><p>

```
'org.apache.commons.io.input.UnsynchronizedByteArrayInputStream$Builder org.apache.commons.io.input.UnsynchronizedByteArrayInputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.testMaxSheetNameLength</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_NoHeader_StartRow12</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_NoHeader_InlinedStrings_Streaming</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testXLSX</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testXLSXStream</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_MultipleSheets_Header_StartRow0</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_MultipleSheets_Header_StartRowX</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_NoHeader_InlinedStrings_NoStreaming</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_Header_InlinedStrings_Streaming</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_Header_StartRow0</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_Header_StartRow5</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_MultipleSheets_NoHeader_StartRow0</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_MultipleSheets_NoHeader_StartRowX</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testXLSXCompressionRatioIsBig</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_NoHeader_SharedStrings_Streaming</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_Header_InlinedStrings_NoStreaming</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_Header_SharedStrings_Streaming</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_NoHeader_SharedStrings_NoStreaming</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.com [...]

2024-06-04 19:32 UTC, buildguy commented
<div align='center'>

[![🚨 Frogbot scanned this pull request and found the below:](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/vulnerabilitiesBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>


## 📦 Vulnerable Dependencies
### ✍️ Summary
<div align='center'>

| SEVERITY                | DIRECT DEPENDENCIES                  | IMPACTED DEPENDENCY                  | FIXED VERSIONS                  | CVES                  |
| :---------------------: | :-----------------------------------: | :-----------------------------------: | :-----------------------------------: | :-----------------------------------: |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableCriticalSeverity.png)<br>Critical | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.44.Final] | CVE-2019-20445 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableCriticalSeverity.png)<br>Critical | org.apache.activemq:artemis-junit:2.5.0 | org.apache.activemq:artemis-server 2.5.0 | [2.31.2] | CVE-2023-46604 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableCriticalSeverity.png)<br>Critical | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.44.Final] | CVE-2019-20444 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec 4.1.22.Final | [4.1.68.Final] | CVE-2021-37136 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec 4.1.22.Final | [4.1.68.Final] | CVE-2021-37137 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT<br>org.apache.activemq:artemis-jms-client-osgi:2.5.0 | org.apache.activemq:artemis-core-client 2.5.0 | [2.19.1] | CVE-2022-23913 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-handler 4.1.22.Final | [4.1.46] | CVE-2020-11612 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-junit:2.5.0 | org.apache.activemq:artemis-server 2.5.0 | [2.24.0] | CVE-2022-35278 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-handler 4.1.22.Final | [4.1.94.Final] | CVE-2023-34462 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.71.Final] | CVE-2021-43797 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | org.apache.activemq:artemis-core-client 2.5.0 | [2.19.1] | CVE-2021-4040 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.108.Final] | CVE-2024-29025 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT<br>org.apache.activemq:artemis-jms-client-osgi:2.5.0 | io.netty:netty-codec-http 4.1.22.Final | [4.1.77.Final] | CVE-2022-24823 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT<br>org.apache.activemq:artemis-jms-client-osgi:2.5.0 | io.netty:netty-codec-http 4.1.22.Final | [4.1.59.Final] | CVE-2021-21290 |

</div>

<details>
<summary> <b>🔬 Research Details</b> </summary>
<br>

<details>
<summary> <b>[ CVE-2019-20445 ] io.netty:netty-codec-http 4.1.22.Final</b> </summary>
<br>


**Description:**
HttpObjectDecoder.java in Netty before 4.1.44 allows a Content-Length header to be accompanied by a second Content-Length header, or by a Transfer-Encoding header.

</details>

<details>
<summary> <b>[ CVE-2023-46604 ] org.apache.activemq:artemis-server 2.5.0</b> </summary>
<br>


**Description:**
[Apache ActiveMQ](https://activemq.apache.org/) is a widely-used open-source message broker written in Java, known for its multi-protocol compatibility. It offers clients the flexibility of choosing from various programming languages and platforms, with support for JavaScript, C, C++, Python, .NET, and others.

[Apache ActiveMQ Artemis](https://activemq.apache.org/components/artemis/) is a next-generation, high-performance message broker, designed as a successor to the classic Apache ActiveMQ, offering improved performance, scalability, and a more modern architecture for messaging applications.

ActiveMQ can broker multiple protocol formats, such as AMQP, STOMP, MQTT, and OpenWire.
The OpenWire implementation in ActiveMQ was discovered to be vulnerable to a deserialization attack, which may lead to remote code execution by unauthenticated network attackers.

The vulnerability is highly likely to be exploited, since it is exploitable by unauthenticated network attackers, in the default ActiveMQ server configuration, by using a public exploit and with no need for target-specific research.

Successful exploitation requires a class on the classpath to be used as a gadget, which can execute arbitrary code simply by instantiating it with a String parameter.

One of the classes shipped in the classic ActiveMQ is `org.springframework.context.support.ClassPathXmlApplicationContext`.
The purpose of `ClassPathXmlApplicationContext` is to retrieve an XML application configuration file via HTTP from a remote location on the network, which is used in the published PoCs to execute arbitrary code.

The Artemis versions also support the OpenWire protocol but does not ship with this gadget class, so exploitation of Artemis has not yet been proven.

The OpenWire transport is enabled by default and listens on TCP port 61616.

**Remediation:**
##### Deployment mitigations

You can switch from using the vulnerable `OpenWire` protocol to another protocol (and adjust the MQTT clients accordingly).

On ActiveMQ (the default Classic project):
In the configuration file `activemq.xml` change the transport connector to one of the following - AMQP / MQTT / STOMP / Websockets.

An example of a vulnerable transport connector:
```
<transportConnector name="tcp" uri="tcp://0.0.0.0:61616"/>
```

An example of non-vulnerable transport connectors:
```
<transportConnector name="amqp" uri="amqp://0.0.0.0:5672"/>
<transportConnector name="stomp" uri="stomp://0.0.0.0:61613"/>
<transportConnector name="mqtt" uri="mqtt://0.0.0.0:1883"/>
<transportConnector name="ws" uri=" [...]

2024-06-04 19:40 UTC, buildguy commented
<div align='center'>

[![🚨 Frogbot scanned this pull request and found the below:](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/vulnerabilitiesBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>


## 📦 Vulnerable Dependencies
### ✍️ Summary
<div align='center'>

| SEVERITY                | DIRECT DEPENDENCIES                  | IMPACTED DEPENDENCY                  | FIXED VERSIONS                  | CVES                  |
| :---------------------: | :-----------------------------------: | :-----------------------------------: | :-----------------------------------: | :-----------------------------------: |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableCriticalSeverity.png)<br>Critical | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.44.Final] | CVE-2019-20444 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableCriticalSeverity.png)<br>Critical | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.44.Final] | CVE-2019-20445 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableCriticalSeverity.png)<br>Critical | org.apache.activemq:artemis-junit:2.5.0 | org.apache.activemq:artemis-server 2.5.0 | [2.31.2] | CVE-2023-46604 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-handler 4.1.22.Final | [4.1.46] | CVE-2020-11612 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec 4.1.22.Final | [4.1.68.Final] | CVE-2021-37136 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec 4.1.22.Final | [4.1.68.Final] | CVE-2021-37137 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableHighSeverity.png)<br>    High | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | org.apache.activemq:artemis-core-client 2.5.0 | [2.19.1] | CVE-2022-23913 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT<br>org.apache.activemq:artemis-jms-client-osgi:2.5.0 | io.netty:netty-codec-http 4.1.22.Final | [4.1.71.Final] | CVE-2021-43797 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-handler 4.1.22.Final | [4.1.94.Final] | CVE-2023-34462 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-junit:2.5.0 | org.apache.activemq:artemis-server 2.5.0 | [2.24.0] | CVE-2022-35278 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.108.Final] | CVE-2024-29025 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | org.apache.activemq:artemis-core-client 2.5.0 | [2.19.1] | CVE-2021-4040 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.77.Final] | CVE-2022-24823 |
| ![](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/applicableMediumSeverity.png)<br>  Medium | org.apache.activemq:artemis-jms-client-osgi:2.5.0<br>org.pentaho.di.plugins:pentaho-streaming-jms-plugin:10.2.0.0-SNAPSHOT | io.netty:netty-codec-http 4.1.22.Final | [4.1.59.Final] | CVE-2021-21290 |

</div>

<details>
<summary> <b>🔬 Research Details</b> </summary>
<br>

<details>
<summary> <b>[ CVE-2019-20444 ] io.netty:netty-codec-http 4.1.22.Final</b> </summary>
<br>


**Description:**
HttpObjectDecoder.java in Netty before 4.1.44 allows an HTTP header that lacks a colon, which might be interpreted as a separate header with an incorrect syntax, or might be interpreted as an "invalid fold."

</details>

<details>
<summary> <b>[ CVE-2019-20445 ] io.netty:netty-codec-http 4.1.22.Final</b> </summary>
<br>


**Description:**
HttpObjectDecoder.java in Netty before 4.1.44 allows a Content-Length header to be accompanied by a second Content-Length header, or by a Transfer-Encoding header.

</details>

<details>
<summary> <b>[ CVE-2023-46604 ] org.apache.activemq:artemis-server 2.5.0</b> </summary>
<br>


**Description:**
[Apache ActiveMQ](https://activemq.apache.org/) is a widely-used open-source message broker written in Java, known for its multi-protocol compatibility. It offers clients the flexibility of choosing from various programming languages and platforms, with support for JavaScript, C, C++, Python, .NET, and others.

[Apache ActiveMQ Artemis](https://activemq.apache.org/components/artemis/) is a next-generation, high-performance message broker, designed as a successor to the classic Apache ActiveMQ, offering improved performance, scalability, and a more modern architecture for messaging applications.

ActiveMQ can broker multiple protocol formats, such as AMQP, STOMP, MQTT, and OpenWire.
The OpenWire implementation in ActiveMQ was discovered to be vulnerable to a deserialization attack, which may lead to remote code execution by unauthenticated network attackers.

The vulnerability is highly likely to be exploited, since it is exploitable by unauthenticated network attackers, in the default ActiveMQ server configuration, by using a public exploit and with no need for target-specific research.

Successful exploitation requires a class on the classpath to be used as a gadget, which can execute arbitrary code simply by instantiating it with a String parameter.

One of the classes shipped in the classic ActiveMQ is `org.springframework.context.support.ClassPathXmlApplicationContext`.
The purpose of `ClassPathXmlApplicationContext` is to retrieve an XML application configuration file via HTTP from a remote location on the network, which is used in the published PoCs to execute arbitrary code.

The Artemis versions also support the OpenWire protocol but does not ship with this gadget class, so exploitation of Artemis has not yet been proven.

The OpenWire transport is enabled by default and listens on TCP port 61616.

**Remediation:**
##### Deployment mitigations

You can switch from using the vulnerable `OpenWire` protocol to another protocol (and adjust the MQTT clients accordingly).

On ActiveMQ (the default Classic project):
In the configuration file `activemq.xml` change the transport connector to one of the following - AMQP / MQTT / STOMP / Websockets.

An example of a vulnerable transport connector:
 [...]

2024-06-04 19:40 UTC, buildguy commented
### :x: Build failed in 43m 4s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 158 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.test_Xls_Template</b> (click to expand)</summary><p>

```
'org.apache.commons.io.input.UnsynchronizedByteArrayInputStream$Builder org.apache.commons.io.input.UnsynchronizedByteArrayInputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.test_Xls_Template</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.test_Xls_NoTemplate</b> (click to expand)</summary><p>

```
'org.apache.commons.io.input.UnsynchronizedByteArrayInputStream$Builder org.apache.commons.io.input.UnsynchronizedByteArrayInputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.test_Xls_NoTemplate</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.testProtectSheet</b> (click to expand)</summary><p>

```
'org.apache.commons.io.input.UnsynchronizedByteArrayInputStream$Builder org.apache.commons.io.input.UnsynchronizedByteArrayInputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.testProtectSheet</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.testMaxSheetNameLength</b> (click to expand)</summary><p>

```
'org.apache.commons.io.input.UnsynchronizedByteArrayInputStream$Builder org.apache.commons.io.input.UnsynchronizedByteArrayInputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepTest.testMaxSheetNameLength</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_NoHeader_StartRow12</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_NoHeader_InlinedStrings_Streaming</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testXLSX</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testXLSXStream</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_MultipleSheets_Header_StartRow0</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_MultipleSheets_Header_StartRowX</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_NoHeader_InlinedStrings_NoStreaming</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_Header_InlinedStrings_Streaming</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_Header_StartRow0</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_SingleSheet_Header_StartRow5</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_MultipleSheets_NoHeader_StartRow0</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.test_PDI_17765_MultipleSheets_NoHeader_StartRowX</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testXLSXCompressionRatioIsBig</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_NoHeader_SharedStrings_Streaming</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_Header_InlinedStrings_NoStreaming</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_Header_SharedStrings_Streaming</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testReadBlankAndNullCells_XSLSX_NoHeader_SharedStrings_NoStreaming</b> (click to expand)</summary><p>

```
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.comm [...]

2024-06-26 10:29 UTC, closed without merging