[BACKLOG-40258][BACKLOG-41446] Fix test failure
pentaho/pentaho-kettle pull request #9470
Opened 2024-07-12 00:07 UTC by niehusa

2024-07-12 14:34 UTC, bconlon-hv requested changes
Why are we removing error-handling code from kitchen itself?

2024-07-12 16:16 UTC, niehusa commented
> Why are we removing error-handling code from kitchen itself?

We don't need it at the end of Kitchen.main() method so remove it.

2024-07-15 13:19 UTC, bconlon-hv approved these changes

2024-07-15 13:20 UTC, bconlon-hv commented
Approved.  Was concerned that we were removing some old kitchen logic, but it's just something new that we've added only on our side branch.

2024-07-15 19:49 UTC, pdesai16 approved these changes

2024-07-15 19:49 UTC, merged