[PPP-4899] Vulnerable Component: commons-io
pentaho/pentaho-kettle pull request #9525
Opened 2024-08-12 23:18 UTC by singletonc

Jira: https://hv-eng.atlassian.net/browse/PPP-4899

- upgrade eclipse ui workbench version 3.127.0 -> 3.132.0 -- This gets us to commons-io 2.11.0, which is 2.7+, addressing CVE-2021-29425
- libloader case handled in https://github.com/pentaho/pentaho-reporting/pull/1678

```
[INFO] |  +- org.eclipse.platform:org.eclipse.ui.workbench:jar:3.132.0:compile
...
[INFO] |  |  +- org.eclipse.platform:org.eclipse.e4.ui.workbench.swt:jar:0.17.400:compile
...
[INFO] |  |  |  +- org.eclipse.platform:org.eclipse.e4.ui.css.core:jar:0.14.400:compile
[INFO] |  |  |  |  \- org.apache.xmlgraphics:batik-css:jar:1.17:compile
...
[INFO] |  |  |  |     \- org.apache.xmlgraphics:xmlgraphics-commons:jar:2.9:compile
[INFO] |  |  |  |        +- commons-io:commons-io:jar:2.11.0:compile
```

2024-08-12 23:44 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-08-12 23:44 UTC, buildguy commented
### :white_check_mark: Build finished in 25m 4s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
plugins/file-open-save-new/core
```
---
:ok_hand: All tests passed!
 
Tests run: **60**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9525/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-08-13 13:36 UTC, NJtwentyone approved these changes

2024-08-13 21:02 UTC, NJtwentyone requested changes
please identify QA tests per - https://hv-eng.atlassian.net/wiki/spaces/ENG/pages/31277645984/Recommended+process+when+reviewing+and+addressing+security+vulnerabilities

and please link or add comment to original jira issue

2024-08-20 21:13 UTC, singletonc commented
> please identify QA tests per - https://hv-eng.atlassian.net/wiki/spaces/ENG/pages/31277645984/Recommended+process+when+reviewing+and+addressing+security+vulnerabilities
> 
> and please link or add comment to original jira issue

This is covered in this test case https://eu1-prod.practitest.app/p/13675/tests/2290690

More details in Jira comment https://hv-eng.atlassian.net/browse/PPP-4899?focusedCommentId=2050526

2024-08-30 19:31 UTC, merged