[BACKLOG-40521] Display the PartitionSchema at project, global an local
pentaho/pentaho-kettle pull request #9691
Opened 2024-11-05 21:54 UTC by pdesai16

level and provided right click menu items
 - Added right click menuitems and actions for PartitionSchema

2024-11-05 22:11 UTC, niehusa approved these changes

2024-11-06 13:26 UTC, abryant-hv requested changes

2024-11-06 17:28 UTC, abryant-hv commented on engine/src/main/java/org/pentaho/di/trans/TransMeta.java
> +      return localPartitionSchemaMgr.getAll();
As discussed in the meeting, this should be the read manager

2024-11-06 17:28 UTC, abryant-hv commented on engine/src/main/java/org/pentaho/di/trans/TransMeta.java
> +      List<PartitionSchema> partitionSchemas = localPartitionSchemaMgr.getAll();
As discussed in the meeting, this should be the read manager

2024-11-06 19:31 UTC, pdesai16 commented on ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java
> +    {
I don't see the IDE using our checkstyle is flagging this as incorrect. I am changing it anyway

2024-11-06 21:35 UTC, abryant-hv approved these changes

2024-11-06 21:35 UTC, merged