[PPP-5384]-XSS Findings for Pentaho-kettle
pentaho/pentaho-kettle pull request #9694
Opened 2024-11-06 09:08 UTC by Rangashivani

[PPP-5384]-XSS Findings for Pentaho-kettle

2024-11-06 09:32 UTC, buildguy commented
[comment]: <> (FrogbotReviewComment)

<div align='center'>

[![👍 Frogbot scanned this pull request and did not find any new security issues.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-11-06 09:32 UTC, buildguy commented
### :white_check_mark: Build finished in 23m 59s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl plugins/core-ui
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

2024-11-07 12:58 UTC, dcleao requested changes

2024-11-07 12:58 UTC, dcleao commented on plugins/core-ui/src/main/resources/app/pentaho/util/url.js
> +      hostname: xssUtil.sanitizeHtml(host),
I don't understand what we are trying to fix here. The JIRA issue does not also list the App Scan findings.

2024-11-12 06:58 UTC, closed without merging